
# html lang
language: en

# main menu navigation
menu:
  首页: /
  关于: /about
#  Contact: /contact
  文章: /archives

# stylesheets loaded in the <head>
stylesheets:
    - /css/style.css
    - /css/index.css
    - /css/post.css

# scripts loaded in the end of the body
scripts:
    - /js/noone.js

# ========= Images =========
banner_image: "images/bg.png"
avatar_image: "images/avatar.jpg"