
# html lang
language: en

# main menu navigation
menu:
  首页: /
#  Contact: /contact
  目录: /archives
  关于: /about    

# stylesheets loaded in the <head>
stylesheets:
    - /css/style.css
    - /css/index.css
    - /css/post.css
    - /css/archive.css

# scripts loaded in the end of the body
scripts:
    - /js/jquery-3.6.0.min.js
    - /js/noone.js
    - /js/post.js  

# ========= Images =========
banner_image: "images/bg.jpg"
avatar_image: "images/avatar.jpg"

# ========= 备案信息 =========
record: "蜀ICP备19016566号"
record_url: "https://beian.miit.gov.cn/"